const NOTIFICATION_DURATION_MS = 5000
const NOTIFICATION_EXIT_DURATION_MS = 140
const MAX_VISIBLE_NOTIFICATIONS = 4

export {
  MAX_VISIBLE_NOTIFICATIONS,
  NOTIFICATION_DURATION_MS,
  NOTIFICATION_EXIT_DURATION_MS,
}
